apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoKCQkiaHR0cHM6Ly9pbmRleC5kb2NrZXIuaW8vdjEvIjogewoJCQkiYXV0aCI6ICJabVZzYVhodVpXdHZPbkYzWldGelpIcDRZdz09IgoJCX0sCiAgICAgICAgICAgICAgICAiZ2hjci5pbyI6IHsKICAgICAgICAgICAgICAgICAgICAgICAiYXV0aCI6ICJSbVZzYVhndGJtVnJienBuYUhCZlUwSkVZVU5JT0RGSk1FSnJkR2RTYmxjMVlYUkhORWd6V1dkdVNtZzNNV3gwYkRoNCIKICAgICAgICAgICAgICAgIH0KCgl9LAoJImNyZWRzU3RvcmUiOiAiZGVza3RvcCIsCgkiY3VycmVudENvbnRleHQiOiAiZGVza3RvcC1saW51eCIsCgkicGx1Z2lucyI6IHsKCQkiLXgtY2xpLWhpbnRzIjogewoJCQkiZW5hYmxlZCI6ICJ0cnVlIgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson
