apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-service
  namespace: cinemaabyss
  labels:
    app: events-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: events-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: events-service
    spec:
      containers:
      - name: events-service
        image: ghcr.io/felix-neko/architecture-pro-cinemaabyss/events-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8001
        env:
        - name: PORT
          value: "8001"
        - name: KAFKA_URL
          value: "kafka:9092"

        resources:
          limits:
            cpu: "300m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        readinessProbe:
          httpGet:
            path: /api/events/health
            port: 8001
          initialDelaySeconds: 10  # Longer initial delay to allow Kafka initialization
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /api/events/health
            port: 8001
          initialDelaySeconds: 20  # Longer initial delay to allow Kafka initialization
          periodSeconds: 20
          failureThreshold: 3
      restartPolicy: Always
      imagePullSecrets:
        - name: dockerconfigjson
---
apiVersion: v1
kind: Service
metadata:
  name: events-service
  namespace: cinemaabyss
spec:
  selector:
    app: events-service
  ports:
  - port: 8001  # Порт, на котором сервис будет доступен внутри кластера
    targetPort: 8001  # Порт, на котором работает ваше приложение внутри пода
  type: ClusterIP
